### ISSUE TITLE
USERSTORY: Signup form

### ISSUE THREAD

**Issue by Vanhouttestien** [Vanhouttestien/languageteachtool#4]
As I user I can sign up to get access to features for logged-in users

### Acceptance criteria
- [x] There is a sign-in form 
- [x] When logged-in, user gets access to features for logged-in users

### Tasks
- [x] Create Sign-in form
- [x] Add authorization to pages
